- "<%= entity %> SUCKS MORE THAN A SUCK MACHINE SET TO 'SUCK A LOT'."
- "<%= entity %>, HOW DO YOU LIKE DEM APPLES?"
- "<%= entity %>: MEDIOCRE!"
- "NO NO NO, NOT IN MY HOUSE, <%= entity %>!"
- "<%= entity %> is G.O.A.T.: GARBAGEST OF ALL TIME"
- "HEY <%= entity %>, YOU SUCK!"
- "THERE'S ALWAYS NEXT YEAR, <%= entity %>."
- "<%= entity %> POURS THEIR MILK BEFORE THEIR CEREAL"
- "UGH <%= entity %> IS THE WORST"
- "<%= entity %> SAD!"
- "SUCH LOW ENERGY, <%= entity %>"
- "DO U EVEN BASKETBALL <%= entity %>?"
- "YOU KNOW THE POINT IS TO WIN RIGHT, <%= entity %>?"
- "YOU CAN'T SPELL '<%= entity %> IS TRASH' WITHOUT '<%= entity %>'"
- "<%= entity %>, THAT WAS HONESTLY WORSE THAN THE TIME OUR DATACENTER GOT FLOODED"
- "<%= entity %> NEEDS A NEW PAIR OF GLASSES"
- "<%= entity %> MUST'VE BEEN DRUNK"
- "WEAK SAUCE, <%= entity %>"
- "LOL <%= entity %>"
- "<%= entity %>, NICE TRY... NOT!" 
- "YOU PLAYED YOURSELF, <%= entity %>"
- "IN MEMORIUM <%= entity %> 2017-2017"
- "YOU'RE SUCH A JOKE DAVE CHAPELLE DID AN ENTIRE SPECIAL ABOUT YOU ON NETFLIX, <%= entity %>"
- "YOU CAN'T LOSE IF YOU WERE NEVER IN IT TO BEGIN WITH, <%= entity %>"
- "CONGRATULATIONS TO <%= entity %> ON BREAKING THE ALL-TIME RECORD FOR LOSING"
- "Q-U-A-L-I-T-Y L-O-S-S <%= entity %>"
- "<%= entity %> YOUR GAME IS BAD AND YOU SHOULD FEEL BAD"
- "<%= entity %> IS OVERRATED AF"
- "EVERYTHING >>>> <%= entity %>"
- "<%= entity %> LOST AGAIN NO SURPRISES THERE"
- "<%= entity %> PUTS THE L IN LAME"
- "<%= entity %> THE JERK STORE CALLED, THEY'RE RUNNING OUT OF YOU"
- "BALL DON'T LIE <%= entity %>"
- "<%= entity %> STINKS MORE THAN FISH MICROWAVED IN THE OFFICE"
- "<%= entity %> LOVES BLACK LICORICE"
- "<%= entity %> IS WORSE THAN SLOW WALKING TOURISTS"
- "<%= entity %> DOESN'T WAIT FOR PEOPLE TO GET OFF THE SUBWAY BEFORE TRYING TO GET ON"
- "<%= entity %> ONLY TEXTS BACK 'K' LIKE ALL THE TIME WTF"
- "I'VE GOTTEN SPAM EMAILS THAT WERE BETTER THAN <%= entity %>"
